BACKGROUND_FILE_PATH: "./Data/background/original"
SAMPLE_FILES_PATH: "./Data/GermanFlag"
OUTPUT_PATH: "./Data/GermanFlag/TrainingDataComplex2"
BACKGROUND_COLOR : 255
BACKGROUND_THRESH : 8
MAX_X_ANGLE: 30
MAX_Y_ANGLE: 30
MAX_Z_ANGLE: 30
MAX_AFFINE_ANGLE: 75
AFFINE_ROT_PROB: 0.4
PERSP_TRANS_PROB: 0.3
GAUSS_NOISE_PROB: 0.4
MEDIAN_NOISE_PROB: 0.4
SHARPEN_PROB: 0.3
OUTPUT_PER_SAMPLE: 50
SCALING_PROB: 0.6
BRIGHTNESS_PROB: 0.5
